livestock_farming_management_system/animal/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#  Uniquely identify URL name for Animal module
app_name = "animal"

# Define URL patterns to be mapped respective view function of Animal module
urlpatterns = [
    path('',views.animalIndex,name='animalIndex'),
    path('mainAnimal/',views.mainAnimal,name='mainAnimal'),
    path('allAnimals/',views.allAnimals,name='allAnimals'),
    path('mainAnimal/mainCattle/',views.mainCattle,name='mainCattle'),
    path('mainAnimal/mainSheep/',views.mainSheep,name='mainSheep'),
    path('mainAnimal/mainCattle/addCattle/',views.addCattle,name='addCattle'),
    path('mainAnimal/mainCattle/updateCattle/<str:id>',views.updateCattle,name='updateCattle'),
    path('mainAnimal/mainCattle/viewCattle/<str:id>',views.viewCattle,name='viewCattle'),
    path('mainAnimal/mainCattle/deleteCattle/<str:id>',views.deleteCattle,name='deleteCattle'),
    path('mainAnimal/mainCattle/addCattleGroup/',views.addCattleGroup,name='addCattleGroup'),
    path('mainAnimal/mainCattle/viewRelatedCattle/<str:id>',views.viewRelatedCattle,name='viewRelatedCattle'),
    path('mainAnimal/mainCattle/searchCattle/',views.searchCattle,name='searchCattle'),
    path('mainAnimal/mainSheep/addSheep/',views.addSheep,name='addSheep'),
    path('mainAnimal/mainSheep/updateSheep/<str:id>',views.updateSheep,name='updateSheep'),
    path('mainAnimal/mainSheep/viewSheep/<str:id>',views.viewSheep,name='viewSheep'),
    path('mainAnimal/mainSheep/deleteSheep/<str:id>',views.deleteSheep,name='deleteSheep'),
    path('mainAnimal/mainSheep/addSheepGroup/',views.addSheepGroup,name='addSheepGroup'),
    path('mainAnimal/mainSheep/viewRelatedSheep/<str:id>',views.viewRelatedSheep,name='viewRelatedSheep'),
    path('mainAnimal/mainSheep/searchSheep/',views.searchSheep,name='searchSheep'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

livestock_farming_management_system/livestock_farming_management_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('user.urls')),
    path('equipment/',include('equipment.urls')),
    path('task/',include('task.urls')),
    path('animal/',include('animal.urls')),
    path('financial/',include('financial.urls')),
    path('admin/', admin.site.urls),
]

livestock_farming_management_system/task/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#  Uniquely identify URL name for Task module
app_name = "task"

# Define URL patterns to be mapped respective view function of Task module
urlpatterns = [
    path('',views.taskIndex,name='taskIndex'),
    path('mainTask/',views.mainTask,name='mainTask'),
    path('addTask/',views.addTask,name='addTask'),
    path('viewTask/<str:id>',views.viewTask,name='viewTask'),
    path('updateTask/<str:id>',views.updateTask,name='updateTask'),
    path('deleteTask/<str:id>',views.deleteTask,name='deleteTask'),
    path('myTask/',views.myTask,name='myTask'),
    path('updateTaskStatus/<str:id>',views.updateTaskStatus,name='updateTaskStatus'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

livestock_farming_management_system/animal/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.db import IntegrityError
from django.core.files.storage import FileSystemStorage
from animal.models import Cattle, CattleGroup, CattleGrouping, Sheep, SheepGroup, SheepGrouping
from django.utils import timezone
from user.models import User
from django.db.models import Q
import datetime
# Create your views here.


# Represents the homepage or root URL of Animal module. It will redirect system to the mainAnimal view function.
def animalIndex(request):
    return redirect('animal:mainAnimal')


# Renders main animal page with several categories of animals
def mainAnimal(request):
    user = User.objects.get(email = request.session['EMAIL'])

    calvingCow=Cattle.objects.filter(cattleType="COW",cattleStatus="ACTIVE").count()
    calvingEwe=Sheep.objects.filter(sheepType="EWE",sheepStatus="ACTIVE").count()
    breedingBull=Cattle.objects.filter(cattleType="BULL",cattleStatus="ACTIVE").count()
    breedingRam=Sheep.objects.filter(sheepType="RAM",sheepStatus="ACTIVE").count()
    weaningCattle=Cattle.objects.filter(cattleWeaningStatus="YES",cattleStatus="ACTIVE").count()
    weaningSheep=Sheep.objects.filter(sheepWeaningStatus="YES",sheepStatus="ACTIVE").count()
    today=datetime.datetime.now()
    yearlingCattle=Cattle.objects.filter(cattleBirthDate__gte=timezone.now()-timezone.timedelta(weeks=72)).count()
    yearlingSheep=Sheep.objects.filter(sheepBirthDate__gte=today-datetime.timedelta(weeks=72)).count()
    return render(request, 'mainAnimal.html', {'user':user,'breedingBull':breedingBull,'breedingRam':breedingRam,'weaningCattle':weaningCattle,'weaningSheep':weaningSheep,'calvingCow':calvingCow,'calvingEwe':calvingEwe,'yearlingCattle':yearlingCattle,'yearlingSheep':yearlingSheep})


# Renders all animals page with animal records
def allAnimals(request):
    user = User.objects.get(email = request.session['EMAIL'])
    cattle=Cattle.objects.all()
    sheep=Sheep.objects.all()
    allAnimals=[]
    allAnimals.append(cattle)
    allAnimals.append(sheep)
    return render(request, 'allAnimals.html', {'user':user,'cattle':cattle,'sheep':sheep,'allAnimals':allAnimals})


# cattle-related views

# Renders main cattle page with latest cattles and cattle groups
def mainCattle(request):
    user = User.objects.get(email = request.session['EMAIL'])
    allCattle=Cattle.objects.all()
    activeBulls=Cattle.objects.all().filter(cattleType='BULL',cattleStatus='ACTIVE')
    activeCows=Cattle.objects.all().filter(cattleType='COW',cattleStatus='ACTIVE')
    activeCalves=Cattle.objects.all().filter(cattleType='CALF',cattleStatus='ACTIVE')
    activeCattle=Cattle.objects.all().filter(cattleStatus='ACTIVE')
    purchasedCattle=Cattle.objects.all().filter(cattleRaisedOrPurchased='PURCHASED')
    soldCattle=Cattle.objects.all().filter(cattleStatus='SOLD')
    cattleGroups=CattleGroup.objects.all()
    return render(request, 'mainCattle.html', {'user':user,'allCattle':allCattle,'activeBulls':activeBulls,'activeCows':activeCows,'activeCalves':activeCalves,'activeCattle':activeCattle,'purchasedCattle':purchasedCattle,'soldCattle':soldCattle,'cattleGroups':cattleGroups})


# Handles addition of new cattle
def addCattle(request):
    user = User.objects.get(email = request.session['EMAIL'])
    cattleGroups = CattleGroup.objects.all()
    possibleDam = Cattle.objects.all().filter(cattleType='COW')
    possibleSire = Cattle.objects.all().filter(cattleType='BULL')
    try:

        if request.method=='POST':
            tagID=request.POST.get('tagID')
            tagPosition=request.POST.get('tagPosition')
            type=request.POST.get('type')
            status=request.POST.get('status')
            breed=request.POST.get('breed')
            hornStatus=request.POST.get('hornStatus')
            weaningStatus=request.POST.get('weaningStatus')
            imgupload = request.FILES.get('fileupload', None)
            remark=request.POST.get('remark')
            purchasedOrNot=request.POST.get('purchasedOrNot')
            offerPrice=request.POST.get('offerPrice') or None
            marketingNote=request.POST.get('marketingNote')
            birthdate=request.POST.get('birthdate') or None
            birthWeight=request.POST.get('birthWeight') or None
            sire=request.POST.get('sire') or None
            if sire:
                sire = Cattle.objects.get(id=sire)
            dam=request.POST.get('dam') or None
            if dam:
                dam = Cattle.objects.get(id=dam)

            cattleID=Cattle(cattleTagID=tagID,cattleTagPosition=tagPosition,cattleType=type,cattleStatus=status,cattleHornStatus=hornStatus,cattleBreed=breed,cattleComment=remark,cattleAttachment=imgupload,cattleOfferPrice=offerPrice,cattleRaisedOrPurchased=purchasedOrNot,cattleCommercialNote=marketingNote,cattleBirthDate=birthdate,cattleBirthWeight=birthWeight,cattleWeaningStatus=weaningStatus,cattleLastUpdatedBy=user,cattleSire=sire,cattleDam=dam).save()
            cattle=Cattle.objects.get(id=cattleID)
            groups=request.POST.getlist('cattleGroup')
            for cattleGroup in groups:
                group=CattleGroup.objects.get(id=cattleGroup)
                CattleGrouping(c_cattleID=cattle,cg_cattleGroup=group).save()

            messages.success(request,'Cattle record is successfully created.', extra_tags='addCattle')
            return redirect('animal:mainCattle')
        else:
            return render(request, 'addCattle.html', {'user':user,'cattleGroups':cattleGroups,'possibleDam':possibleDam,'possibleSire':possibleSire})

    except Exception as e:
        # messages.error(request,'Error cattle'+e)
        raise e
        return render(request, 'addCattle.html', {'user':user,'cattleGroups':cattleGroups,'possibleDam':possibleDam,'possibleSire':possibleSire})


# Handles update operation of exisiting cattle
def updateCattle(request,id):
    user = User.objects.get(email = request.session['EMAIL'])
    cattle = Cattle.objects.get(id = id)
    cattleGroups = CattleGroup.objects.all()
    possibleDam = Cattle.objects.all().filter(cattleType='COW').exclude(id=cattle.id)
    possibleSire = Cattle.objects.all().filter(cattleType='BULL').exclude(id=cattle.id)
    currentGrouping=CattleGrouping.objects.filter(c_cattleID=cattle)
    if request.method=='POST':
        cattle.cattleTagID=request.POST.get('tagID')
        cattle.cattleTagPosition=request.POST.get('tagPosition')
        cattle.cattleType=request.POST.get('type')
        cattle.cattleStatus=request.POST.get('status')
        cattle.cattleBreed=request.POST.get('breed')
        cattle.cattleHornStatus=request.POST.get('hornStatus')
        cattle.cattleWeaningStatus=request.POST.get('weaningStatus')
        if len(request.FILES) != 0:
            if cattle.cattleAttachment!=None or cattle.cattleAttachment!='':
                cattle.cattleAttachment.delete()
            cattle.cattleAttachment = request.FILES['fileupload']
            fss =FileSystemStorage()
        cattle.cattleComment=request.POST.get('remark')
        cattle.cattleRaisedOrPurchased=request.POST.get('purchasedOrNot')
        cattle.cattleOfferPrice=request.POST.get('offerPrice') or None
        cattle.cattleCommercialNote=request.POST.get('marketingNote')
        cattle.cattleBirthDate=request.POST.get('birthdate') or None
        cattle.cattleBirthWeight=request.POST.get('birthWeight') or None
        sire=request.POST.get('sire') or None
        if sire:
            cattle.cattleSire = Cattle.objects.get(id=sire)
        dam=request.POST.get('dam') or None
        if dam:
            cattle.cattleDam = Cattle.objects.get(id=dam)

        cattle.save()

        currentGroup=CattleGrouping.objects.filter(c_cattleID=cattle)
        if currentGroup:
            for grouping in currentGroup:
                grouping.delete()

        groups=request.POST.getlist('cattleGroup')
        for cattleGroup in groups:
            group=CattleGroup.objects.get(id=cattleGroup)
            CattleGrouping(c_cattleID=cattle,cg_cattleGroup=group).save()

        messages.success(request,'Cattle record is successfully updated.', extra_tags='addCattle')
        return redirect('animal:mainCattle')

    return render(request, 'updateCattle.html', {'user':user,'cattle':cattle,'currentGrouping':currentGrouping,'cattleGroups':cattleGroups,'possibleDam':possibleDam,'possibleSire':possibleSire})


# Renders view cattle page with specific record of cattle
def viewCattle(request,id):
    user = User.objects.get(email = request.session['EMAIL'])
    cattle = Cattle.objects.get(id=id)
    currentGrouping=CattleGrouping.objects.filter(c_cattleID=cattle)
    return render(request, 'viewCattle.html', {'user':user,'cattle':cattle,'currentGrouping':currentGrouping})


# Handles deletion of currently exist cattle
def deleteCattle(request,id):
    try:
        user = User.objects.get(email = request.session['EMAIL'])
        cattle = Cattle.objects.get(id = id)
        currentGrouping=CattleGrouping.objects.filter(c_cattleID=cattle)
        if request.method=='POST':
            if cattle.cattleAttachment!=None or cattle.cattleAttachment!='':
                cattle.cattleAttachment.delete()
            cattle.delete()
            messages.success(request,"Cattle is deleted succesfully..!")
            return redirect('animal:mainCattle')
        else:
            return render(request, 'deleteCattle.html', {'user':user,'cattle':cattle,'currentGrouping':currentGrouping})

    except Cattle.DoesNotExist:
        messages.success(request,'No record of the cattle!' + id)
        return redirect('animal:mainCattle')


# Handles addition of new cattle group
def addCattleGroup(request):
    user = User.objects.get(email = request.session['EMAIL'])
    try:

        if request.method=='POST':
            groupName=request.POST.get('groupName')
            CattleGroup(cattleGroupName=groupName).save()

livestock_farming_management_system/animal/templates/allAnimals.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main Cattle</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <style>
        #menu a:hover,
        #menu a.active{
            color: white;
            /* background:white; */
            background: #1D271A;
            /* border-right: 2px solid rgb(96, 122, 138); */
            width: auto;
        }
        .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      #sidebar{
        background-color: #223226;
      }

      #bg-navbar,
      #bg-navbar a{
        background-color: #960017;
        color: white;
      }

      #sidebar-title,
      #sidebar-title a
      {
        background: #7D000F;
        /* margin: -10px; */
        width: 100%;
        text-align: center;
        word-wrap:break-word;
        display: block;
        white-space: normal;
        color: white;
      }
      hr {
        width: 80%; 
        margin-right: auto;
        margin-left: auto;
        color: whitesmoke; 
        height: 1px; 
        background-color:whitesmoke; 
      }
    </style>
    
</head>
<body>
    {% include "sidebarAnimal.html" %}
          <!-- content area! -->
          <div class="col px-0 bg-light">

            <!-- <nav class="navbar sticky-top navbar-light" id="bg-navbar">
              <div class="container-fluid">
                <a class="navbar-brand" href="#">{% now "Y-m-d" %} Hello {{ user.username }}</a>
              </div>
            </nav> -->
            {% include "navbar.html" %}
    
                <h3 class="p-3 bg-white">
                  ANIMALS <br>
                  <small class="text-muted">Management of Animals</small>
                </h3>

                <div class="row g-3 ps-3">
                    <div class="col-sm-7">
                        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                            <li class="nav-item" role="presentation">
                            <button class="nav-link active" id="pills-cattle-tab" data-bs-toggle="pill" data-bs-target="#pills-cattle" type="button" role="tab" aria-controls="pills-cattle" aria-selected="true">Cattle</button>
                            </li>
                            <li class="nav-item" role="presentation">
                            <button class="nav-link" id="pills-sheep-tab" data-bs-toggle="pill" data-bs-target="#pills-sheep" type="button" role="tab" aria-controls="pills-sheep" aria-selected="false">Sheep</button>
                            </li>
                            
                        </ul>
                    </div>
                  </div>                
    
                {% if messages %}
                    <div class="container">
                    <hr>
                    {% for msg in messages %}
                    <b>{{msg}}</b>
                    {% endfor %}
                    </div>
                    <hr>
                {% endif %}
    
                {% if messages %}
                    <div class="container">
                    {% for msg in messages %}
                      {% if "addStaff" in message.tags %}
                        <div class="alert alert-success" role="alert">
                          {{msg}}
                        </div>
                      {% endif %}
                    {% endfor %}
                    </div>
                    <hr>
                {% endif %}
    <!-- 
                <div class="alert alert-success" role="alert">
                  kkk
                </div> -->
    
                <div class="container bg-white">
    
                  <div class="tab-content" id="pills-tabContent">
                    <div class="tab-pane fade show active" id="pills-cattle" role="tabpanel" aria-labelledby="pills-cattle-tab" tabindex="0">
                        <table class="table table-striped table-hover">
                            <thead>
                              <tr>
                                <th scope="col">#</th>
                                <th scope="col">TAG ID</th>
                                <th scope="col">TAG POSITION</th>
                                <th scope="col">BREED</th>
                                <th scope="col">TYPE</th>
                                <th scope="col">STATUS</th>
                                <th scope="col">ACTION</th>
                              </tr>
                            </thead>
                            <tbody class="table-group-divider">
                              {% for cattle in cattle %}
                              <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td>{{cattle.cattleTagID}}</td>
                                <td>{{cattle.cattleTagPosition}}</td>
                                <td>{{cattle.cattleBreed}}</td>
                                <td>{{cattle.cattleType}}</td>
                                <td>{{cattle.cattleStatus}}</td>
                                <td>
                                  <a class="btn btn-info btn-sm" href="{% url 'animal:viewCattle' cattle.id %}" role="button">View</a>
                                  <a class="btn btn-warning btn-sm" href="{% url 'animal:updateCattle' cattle.id %}" role="button">Update</a>
                                  <a class="btn btn-danger btn-sm" href="{% url 'animal:deleteCattle' cattle.id %}" role="button">Delete</a>
                                </td>
                              </tr>
                              {% endfor %}
                            </tbody>
                          </table>
                    </div>
                    <div class="tab-pane fade" id="pills-sheep" role="tabpanel" aria-labelledby="pills-sheep-tab" tabindex="0">
                      <table class="table table-striped table-hover">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">TAG ID</th>
                            <th scope="col">TAG POSITION</th>
                            <th scope="col">BREED</th>
                            <th scope="col">TYPE</th>
                            <th scope="col">STATUS</th>
                            <th scope="col">ACTION</th>
                          </tr>
                        </thead>
                        <tbody class="table-group-divider">
                          {% for sheep in sheep %}
                          <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{sheep.sheepTagID}}</td>
                            <td>{{sheep.sheepTagPosition}}</td>
                            <td>{{sheep.sheepBreed}}</td>
                            <td>{{sheep.sheepType}}</td>
                            <td>{{sheep.sheepStatus}}</td>
                            <td>
                              <a class="btn btn-info btn-sm" href="{% url 'animal:viewSheep' sheep.id %}" role="button">View</a>
                              <a class="btn btn-warning btn-sm" href="{% url 'animal:updateSheep' sheep.id %}" role="button">Update</a>
                              <a class="btn btn-danger btn-sm" href="{% url 'animal:deleteSheep' sheep.id %}" role="button">Delete</a>
                            </td>
                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  
                  </div>


                </div>
              
            
          </div>
          <!-- end of div content area -->


        </div>
      </div>
    
</body>
</html>

livestock_farming_management_system/animal/templates/navbar.html
<nav class="navbar sticky-top navbar-light justify-content-between" id="bg-navbar">
    <a class="navbar-brand px-3">Hello {{ user.username }}</a>  
    <a class="navbar-brand ">{% now "Y-m-d" %}</a>
    <a class="navbar-text px-3" style="text-decoration: none;"> {{ user.userRole }}</a>
  </nav>

livestock_farming_management_system/animal/templates/viewRelatedSheep.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sheep Grouping</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <style>
        #menu a:hover,
        #menu a.active{
            color: white;
            /* background:white; */
            background: #1D271A;
            /* border-right: 2px solid rgb(96, 122, 138); */
            width: auto;
        }
        .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      #sidebar{
        background-color: #223226;
      }

      #bg-navbar,
      #bg-navbar a{
        background-color: #960017;
        color: white;
      }

      #sidebar-title,
      #sidebar-title a
      {
        background: #7D000F;
        /* margin: -10px; */
        width: 100%;
        text-align: center;
        word-wrap:break-word;
        display: block;
        white-space: normal;
        color: white;
      }
      hr {
        width: 80%; 
        margin-right: auto;
        margin-left: auto;
        color: whitesmoke; 
        height: 1px; 
        background-color:whitesmoke; 
      }
    </style>
    
</head>
<body>
    {% include "sidebarAnimal.html" %}
          <!-- content area! -->
          <div class="col px-0 bg-light">

            <!-- <nav class="navbar sticky-top navbar-light" id="bg-navbar">
              <div class="container-fluid">
                <a class="navbar-brand" href="#">{% now "Y-m-d" %} Hello {{ user.username }}</a>
              </div>
            </nav> -->
            {% include "navbar.html" %}
    
                <h3 class="p-3 bg-white">
                  SHEEP <br>
                  <small class="text-muted">Management of Sheep</small>
                </h3>            
    
                {% if messages %}
                    <div class="container">
                    <hr>
                    {% for msg in messages %}
                    <b>{{msg}}</b>
                    {% endfor %}
                    </div>
                    <hr>
                {% endif %}
    
                {% if messages %}
                    <div class="container">
                    {% for msg in messages %}
                      {% if "addStaff" in message.tags %}
                        <div class="alert alert-success" role="alert">
                          {{msg}}
                        </div>
                      {% endif %}
                    {% endfor %}
                    </div>
                    <hr>
                {% endif %}
    <!-- 
                <div class="alert alert-success" role="alert">
                  kkk
                </div> -->

                <div class="container p-2">
                    <nav aria-label="breadcrumb">
                      <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'animal:mainAnimal' %}">Main Animal</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'animal:mainSheep' %}">Main Sheep</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Sheep Based on Grouping</li>
                      </ol>
                    </nav>
                  </div>

                  <h3 class="p-3">
                    <small class="text-muted">{{sheepGroup.sheepGroupName}}
                    </small>
                  </h3>      
    
                <div class="container bg-white">
                  
                    <table class="table table-striped table-hover">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">TAG ID</th>
                            <th scope="col">TAG POSITION</th>
                            <th scope="col">BREED</th>
                            <th scope="col">TYPE</th>
                            <th scope="col">STATUS</th>
                            <th scope="col">ACTION</th>
                          </tr>
                        </thead>
                        <tbody class="table-group-divider">
                          {% for sheep in sheepGrouping %}
                          <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{sheep.s_sheepID.sheepTagID}}</td>
                            <td>{{sheep.s_sheepID.sheepTagPosition}}</td>
                            <td>{{sheep.s_sheepID.sheepBreed}}</td>
                            <td>{{sheep.s_sheepID.sheepType}}</td>
                            <td>{{sheep.s_sheepID.sheepStatus}}</td>
                            <td>
                              <a class="btn btn-info btn-sm" href="{% url 'animal:viewSheep' sheep.s_sheepID.id %}" role="button">View</a>
                              <a class="btn btn-warning btn-sm" href="{% url 'animal:updateSheep' sheep.s_sheepID.id %}" role="button">Update</a>
                              <a class="btn btn-danger btn-sm" href="{% url 'animal:deleteSheep' sheep.s_sheepID.id %}" role="button">Delete</a>
                            </td>
                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>

                </div>
              
            
          </div>
          <!-- end of div content area -->


        </div>
      </div>
    
</body>
</html>