livestock_farming_management_system/financial/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#  Uniquely identify URL name for Financial module
app_name = "financial"

# Define URL patterns to be mapped respective view function of Financial module
urlpatterns = [
    path('',views.financialIndex,name='financialIndex'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('mainFinancial/',views.mainFinancial,name='mainFinancial'),
    path('mainFinancial/mainIncome/',views.mainIncome,name='mainIncome'),
    path('mainFinancial/mainExpense/',views.mainExpense,name='mainExpense'),
    path('mainFinancial/mainSaleTicket/',views.mainSaleTicket,name='mainSaleTicket'),
    path('mainFinancial/mainIncome/addIncome/',views.addIncome,name='addIncome'),
    path('mainFinancial/mainIncome/viewIncome/<str:id>',views.viewIncome,name='viewIncome'),
    path('mainFinancial/mainIncome/updateIncome/<str:id>',views.updateIncome,name='updateIncome'),
    path('mainFinancial/mainIncome/deleteIncome/<str:id>',views.deleteIncome,name='deleteIncome'),
    path('mainFinancial/mainIncome/searchIncome',views.searchIncome,name='searchIncome'),
    path('mainFinancial/mainExpense/addExpense/',views.addExpense,name='addExpense'),
    path('mainFinancial/mainExpense/viewExpense/<str:id>',views.viewExpense,name='viewExpense'),
    path('mainFinancial/mainExpense/updateExpense/<str:id>',views.updateExpense,name='updateExpense'),
    path('mainFinancial/mainExpense/deleteExpense/<str:id>',views.deleteExpense,name='deleteExpense'),
    path('mainFinancial/mainExpense/searchExpense',views.searchExpense,name='searchExpense'),
    path('mainFinancial/mainSaleTicket/addSaleTicket/',views.addSaleTicket,name='addSaleTicket'),
    path('mainFinancial/mainSaleTicket/searchSaleTicket',views.searchSaleTicket,name='searchSaleTicket'),
    path('mainFinancial/mainSaleTicket/updateSaleTicket/<str:id>',views.updateSaleTicket,name='updateSaleTicket'),
    path('mainFinancial/mainSaleTicket/cancelSaleTicket/<str:id>',views.cancelSaleTicket,name='cancelSaleTicket'),
    path('mainFinancial/mainSaleTicket/updateSoldAnimals/<str:id>',views.updateSoldAnimals,name='updateSoldAnimals'),
    path('mainFinancial/mainSaleTicket/viewSaleTicket/<str:id>',views.viewSaleTicket,name='viewSaleTicket'),
    path('mainFinancial/mainSaleTicket/viewSaleTicket/generatedPdf/<str:id>',views.generatedPdf,name='generatedPdf'),
    path('mainFinancial/mainSaleTicket/searchAnimalForSaleTicket/<str:key>',views.searchAnimalForSaleTicket,name='searchAnimalForSaleTicket'),

    
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

livestock_farming_management_system/livestock_farming_management_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('user.urls')),
    path('equipment/',include('equipment.urls')),
    path('task/',include('task.urls')),
    path('animal/',include('animal.urls')),
    path('financial/',include('financial.urls')),
    path('admin/', admin.site.urls),
]

livestock_farming_management_system/task/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#  Uniquely identify URL name for Task module
app_name = "task"

# Define URL patterns to be mapped respective view function of Task module
urlpatterns = [
    path('',views.taskIndex,name='taskIndex'),
    path('mainTask/',views.mainTask,name='mainTask'),
    path('addTask/',views.addTask,name='addTask'),
    path('viewTask/<str:id>',views.viewTask,name='viewTask'),
    path('updateTask/<str:id>',views.updateTask,name='updateTask'),
    path('deleteTask/<str:id>',views.deleteTask,name='deleteTask'),
    path('myTask/',views.myTask,name='myTask'),
    path('updateTaskStatus/<str:id>',views.updateTaskStatus,name='updateTaskStatus'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

livestock_farming_management_system/financial/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib import messages
from django.db.models import Q, Sum
from django.db import IntegrityError
from django.core.files.storage import FileSystemStorage
from financial.models import Expense, Income, SaleTicket, SoldCattle, SoldSheep
import datetime
from django.utils import timezone
from user.models import User
from animal.models import Cattle,Sheep

from io import BytesIO
import os
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.contrib.staticfiles import finders
from django.views.generic import View

# Represents the homapage or root URL of Financial module. It will redirect system to the mainFinancial view function.
def financialIndex(request):
    return redirect('financial:mainFinancial')


# Render dashboard page with latest financial data regarding to business sales and animal inventory
def dashboard(request):
    user = User.objects.get(email = request.session['EMAIL'])
    today=datetime.datetime.now()
    salesYtd = SaleTicket.objects.filter(saleDate__year=today.year, saleTicketInvoiceStatus="VALID")

    janSalesYtd = SaleTicket.objects.filter(saleDate__year=today.year,saleDate__month='1',saleTicketInvoiceStatus="VALID")
    totalJanSalesYtd = sum(total.saleTotalAmount for total in janSalesYtd )

    febSalesYtd = SaleTicket.objects.filter(saleDate__year=today.year,saleDate__month='2',saleTicketInvoiceStatus="VALID")
    totalFebSalesYtd = sum(total.saleTotalAmount for total in febSalesYtd )
    
    macSalesYtd = SaleTicket.objects.filter(saleDate__year=today.year,saleDate__month='3',saleTicketInvoiceStatus="VALID")
    totalMacSalesYtd = sum(total.saleTotalAmount for total in macSalesYtd )
    
    aprSalesYtd = SaleTicket.objects.filter(saleDate__year=today.year,saleDate__month='4',saleTicketInvoiceStatus="VALID")
    totalAprSalesYtd = sum(total.saleTotalAmount for total in aprSalesYtd )
    
    maySalesYtd = SaleTicket.objects.filter(saleDate__year=today.year,saleDate__month='5',saleTicketInvoiceStatus="VALID")
    totalMaySalesYtd = sum(total.saleTotalAmount for total in maySalesYtd )
    
    junSalesYtd = SaleTicket.objects.filter(saleDate__year=today.year,saleDate__month='6',saleTicketInvoiceStatus="VALID")
    totalJunSalesYtd = sum(total.saleTotalAmount for total in junSalesYtd )
    
    julSalesYtd = SaleTicket.objects.filter(saleDate__year=today.year,saleDate__month='7',saleTicketInvoiceStatus="VALID")
    totalJulSalesYtd = sum(total.saleTotalAmount for total in julSalesYtd )
    
    augSalesYtd = SaleTicket.objects.filter(saleDate__year=today.year,saleDate__month='8',saleTicketInvoiceStatus="VALID")
    totalAugSalesYtd = sum(total.saleTotalAmount for total in augSalesYtd )
    
    sepSalesYtd = SaleTicket.objects.filter(saleDate__year=today.year,saleDate__month='9',saleTicketInvoiceStatus="VALID")
    totalSepSalesYtd = sum(total.saleTotalAmount for total in sepSalesYtd )
    
    octSalesYtd = SaleTicket.objects.filter(saleDate__year=today.year,saleDate__month='10',saleTicketInvoiceStatus="VALID")
    totalOctSalesYtd = sum(total.saleTotalAmount for total in octSalesYtd )
    
    novSalesYtd = SaleTicket.objects.filter(saleDate__year=today.year,saleDate__month='11',saleTicketInvoiceStatus="VALID")
    totalNovSalesYtd = sum(total.saleTotalAmount for total in novSalesYtd )
    
    decSalesYtd = SaleTicket.objects.filter(saleDate__year=today.year,saleDate__month='12',saleTicketInvoiceStatus="VALID")
    totalDecSalesYtd = sum(total.saleTotalAmount for total in decSalesYtd )

    salesYtdArray = [totalJanSalesYtd,totalFebSalesYtd,totalMacSalesYtd,totalAprSalesYtd,totalMaySalesYtd,totalJunSalesYtd,totalJulSalesYtd,totalAugSalesYtd,totalSepSalesYtd,totalOctSalesYtd,totalNovSalesYtd,totalDecSalesYtd]

    soldCattleArray=[]
    for x in range(1, 13):
        soldCattle=countSoldCattle(x)
        soldCattleArray.append(soldCattle)

    soldSheepArray=[]
    for x in range(1, 13):
        soldSheep=countSoldSheep(x)
        soldSheepArray.append(soldSheep)


    sumSoldCattleArray=[]
    for x in range(1, 13):
        sumSoldCattle=aggSumSoldCattle(x)
        sumSoldCattleArray.append(sumSoldCattle)

    sumSoldSheepArray=[]
    for x in range(1, 13):
        sumSoldSheep=aggSumSoldSheep(x)
        sumSoldSheepArray.append(sumSoldSheep)


    cattleInfo=[]
    sheepInfo=[]
    calvingCow=Cattle.objects.filter(cattleType="COW",cattleStatus="ACTIVE").count()
    calvingEwe=Sheep.objects.filter(sheepType="EWE",sheepStatus="ACTIVE").count()
    breedingBull=Cattle.objects.filter(cattleType="BULL",cattleStatus="ACTIVE").count()
    breedingRam=Sheep.objects.filter(sheepType="RAM",sheepStatus="ACTIVE").count()
    weaningCattle=Cattle.objects.filter(cattleWeaningStatus="YES",cattleStatus="ACTIVE").count()
    weaningSheep=Sheep.objects.filter(sheepWeaningStatus="YES",sheepStatus="ACTIVE").count()
    today=datetime.datetime.now()
    yearlingCattle=Cattle.objects.filter(cattleBirthDate__gte=timezone.now()-timezone.timedelta(weeks=72)).count()
    yearlingSheep=Sheep.objects.filter(sheepBirthDate__gte=today-datetime.timedelta(weeks=72)).count()
    cattleInfo=[calvingCow,breedingBull,weaningCattle,yearlingCattle]
    sheepInfo=[calvingEwe,breedingRam,weaningSheep,yearlingSheep]

    cattleType=[]
    activeBulls=Cattle.objects.all().filter(cattleType='BULL',cattleStatus='ACTIVE').count
    activeCows=Cattle.objects.all().filter(cattleType='COW',cattleStatus='ACTIVE').count
    activeCalves=Cattle.objects.all().filter(cattleType='CALF',cattleStatus='ACTIVE').count
    sheepType=[]
    activeRam=Sheep.objects.all().filter(sheepType='RAM',sheepStatus='ACTIVE').count
    activeEwe=Sheep.objects.all().filter(sheepType='EWE',sheepStatus='ACTIVE').count
    activeLamb=Sheep.objects.all().filter(sheepType='LAMB',sheepStatus='ACTIVE').count
    cattleType=[activeBulls,activeCows,activeCalves]
    sheepType=[activeRam,activeEwe,activeLamb]

    return render(request,'dashboard.html', {'user':user,'salesYtd':salesYtd, 'yearNow':today.year,'rangeMonth':range(12),'salesYtdArray':salesYtdArray,'soldCattleArray':soldCattleArray,'soldSheepArray':soldSheepArray,'cattleInfo':cattleInfo,'sheepInfo':sheepInfo,'cattleType':cattleType,'sheepType':sheepType, 'sumSoldSheepArray':sumSoldSheepArray,'sumSoldCattleArray':sumSoldCattleArray})


# filter and count number of sold cattle and return the result
def countSoldCattle(month):
    soldCattle=SoldCattle.objects.all().filter(sc_saleTicket__saleDate__month=month, sc_saleTicket__saleTicketInvoiceStatus='VALID').count()
    return soldCattle


# filter and count number of sold sheep and return the result
def countSoldSheep(month):
    soldSheep=SoldSheep.objects.all().filter(ss_saleTicket__saleDate__month=month, ss_saleTicket__saleTicketInvoiceStatus='VALID').count()
    return soldSheep


# filter and count number of sold cattle and return the result
def aggSumSoldCattle(month):
    sumSoldCattle=SoldCattle.objects.all().filter(sc_saleTicket__saleDate__month=month, sc_saleTicket__saleTicketInvoiceStatus='VALID').aggregate(Sum('sc_salePrice'))
    return sumSoldCattle


# filter and count number of sold sheep and return the result
def aggSumSoldSheep(month):
    sumSoldSheep=SoldSheep.objects.all().filter(ss_saleTicket__saleDate__month=month, ss_saleTicket__saleTicketInvoiceStatus='VALID').aggregate(Sum('ss_salePrice'))
    return sumSoldSheep


# Renders main financial page with latest yearly financial information
def mainFinancial(request):
    today=datetime.datetime.now()
    user = User.objects.get(email = request.session['EMAIL'])
    salesYtd = SaleTicket.objects.filter(saleDate__year=today.year, saleTicketInvoiceStatus="VALID")
    marketingYtd = sum(marketingCost.saleMarketingCost for marketingCost in salesYtd)
    
    cattleSold = SoldCattle.objects.filter(sc_saleTicket__in=salesYtd)
    totalCattleSalesYtd=sum(soldCattle.sc_salePrice for soldCattle in cattleSold)
    sheepSold = SoldSheep.objects.filter(ss_saleTicket__in=salesYtd)
    totalSheepSalesYtd=sum(soldSheep.ss_salePrice for soldSheep in sheepSold)
    totalSalesYtd = totalCattleSalesYtd+totalSheepSalesYtd

    incomesYtd = Income.objects.filter(incomeMadeDate__year=today.year)
    totalIncomesYtd = sum(income.incomeAmount for income in incomesYtd)
    expensesYtd = Expense.objects.filter(expenseMadeDate__year=today.year)
    totalExpensesYtd = sum(expense.expenseAmount for expense in expensesYtd)

    grossProfitYtd = totalCattleSalesYtd+totalSheepSalesYtd+totalIncomesYtd-marketingYtd
    netIncomeYtd=grossProfitYtd-totalExpensesYtd

    return render(request, 'mainFinancial.html', {'user':user,'totalSalesYtd':totalSalesYtd,'totalIncomesYtd':totalIncomesYtd,'totalExpensesYtd':totalExpensesYtd,'totalCattleSalesYtd':totalCattleSalesYtd,'totalSheepSalesYtd':totalSheepSalesYtd,'marketingYtd':marketingYtd,'grossProfitYtd':grossProfitYtd,'netIncomeYtd':netIncomeYtd})


# Renders main income page with latest income records
def mainIncome(request):
    user = User.objects.get(email = request.session['EMAIL'])
    incomes = Income.objects.all()
    return render(request, 'mainIncome.html', {'user':user,'incomes':incomes})


# Renders main income page with latest expense records
def mainExpense(request):
    user = User.objects.get(email = request.session['EMAIL'])
    expenses=Expense.objects.all()
    return render(request, 'mainExpense.html', {'user':user,'expenses':expenses})


# Renders main sale ticket page with latest sale ticket records
def mainSaleTicket(request):
    user = User.objects.get(email = request.session['EMAIL'])
    saleTickets=SaleTicket.objects.all()
    return render(request, 'mainSaleTicket.html', {'user':user,'saleTickets':saleTickets})


# Handles addition of new income or renders the add income page
def addIncome(request):

livestock_farming_management_system/financial/templates/mainIncome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main Income</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <style>
        #menu a:hover,
        #menu a.active{
            color: white;
            /* background:white; */
            background: #1D271A;
            /* border-right: 2px solid rgb(96, 122, 138); */
            width: auto;
        }
        .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      #sidebar{
        background-color: #223226;
      }

      #bg-navbar,
      #bg-navbar a{
        background-color: #960017;
        color: white;
      }

      #sidebar-title,
      #sidebar-title a
      {
        background: #7D000F;
        /* margin: -10px; */
        width: 100%;
        text-align: center;
        word-wrap:break-word;
        display: block;
        white-space: normal;
        color: white;
      }
      hr {
        width: 80%; 
        margin-right: auto;
        margin-left: auto;
        color: whitesmoke; 
        height: 1px; 
        background-color:whitesmoke; 
      }
    </style>
    
</head>
<body>
    {% include "sidebarFinancial.html" %}
          <!-- content area! -->
          <div class="col px-0 bg-light">

            <!-- <nav class="navbar sticky-top navbar-light" id="bg-navbar">
              <div class="container-fluid">
                <a class="navbar-brand" href="#">{% now "Y-m-d" %} Hello {{ user.username }}</a>
              </div>
            </nav> -->
            {% include "navbar.html" %}
    
                <h3 class="p-3 bg-white">
                  FINANCIAL <br>
                  <small class="text-muted">Management of Side Income</small>
                </h3>
    
                <nav class="navbar p-3">
                  <div class="container-fluid">
                    <a class="navbar-brand"></a>
                    <form class="d-flex" role="search" method="get" action="{% url 'financial:searchIncome' %}" value="{{request.GET.keyword}}">
                      <input class="form-control me-2" type="search" name="keyword" id="keyword" value="{{request.GET.keyword}}" placeholder="Search" aria-label="Search">
                      <button class="btn btn-outline-success" type="submit" name="submit" value="Search">Search</button>
                    </form>
                  </div>
                </nav>
    
                {% if messages %}
            <div class="container">
            <hr>
            {% for msg in messages %}
            <div class="alert alert-success" role="alert">
              {{msg}}
            </div>
            <!-- <b>{{msg}}</b> -->
            {% endfor %}
            </div>
            <hr>
        {% endif %}
    
                {% if messages %}
                    <div class="container">
                    {% for msg in messages %}
                      {% if "addStaff" in message.tags %}
                        <div class="alert alert-success" role="alert">
                          {{msg}}
                        </div>
                      {% endif %}
                    {% endfor %}
                    </div>
                    <hr>
                {% endif %}
    <!-- 
                <div class="alert alert-success" role="alert">
                  kkk
                </div> -->
    
                <div class="container bg-white">
                  <a class="btn btn-primary m-3" href="{% url 'financial:addIncome' %}" role="button">Add Side Income</a>

                <nav class="container p-2">
                  <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <button class="nav-link active" id="nav-general-tab" data-bs-toggle="tab" data-bs-target="#nav-general" type="button" role="tab" aria-controls="nav-general" aria-selected="true">General</button>
                    <!-- <button class="nav-link" id="nav-open-tab" data-bs-toggle="tab" data-bs-target="#nav-open" type="button" role="tab" aria-controls="nav-open" aria-selected="false">Open</button>
                    <button class="nav-link" id="nav-completed-tab" data-bs-toggle="tab" data-bs-target="#nav-completed" type="button" role="tab" aria-controls="nav-completed" aria-selected="false">Completed</button> -->
                  </div>
                </nav>
                <div class="tab-content" id="nav-tabContent">
                  <div class="tab-pane fade show active container p-2" id="nav-general" role="tabpanel" aria-labelledby="nav-general-tab" tabindex="0">
                    <table class="table table-striped table-hover">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">INCOME ITEM</th>
                          <th scope="col">CUSTOMER</th>
                          <th scope="col">MADE DATE</th>
                          <th scope="col">AMOUNT</th>
                          <th scope="col">LAST UPDATED BY</th>
                          <th scope="col">ACTION</th>
                        </tr>
                      </thead>
                      <tbody class="table-group-divider">
                        {% for income in incomes %}
                        <tr>
                          <th scope="row">{{ forloop.counter }}</th>
                          <td>{{income.incomeItem}}</td>
                          <td>{{income.incomeCustomer}}</td>
                          <td>{{income.incomeMadeDate}}</td>
                          <td>{{income.incomeAmount}}</td>
                          <td>{{income.incomeLastUpdatedBy.username}}</td>
                          <td>
                            <a class="btn btn-info btn-sm" href="{% url 'financial:viewIncome' income.id %}" role="button">View</a>
                            <a class="btn btn-warning btn-sm" href="{% url 'financial:updateIncome' income.id %}" role="button">Update</a>
                            <a class="btn btn-danger btn-sm" href="{% url 'financial:deleteIncome' income.id %}" role="button">Delete</a>
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                  <!-- <div class="tab-pane fade container p-2" id="nav-open" role="tabpanel" aria-labelledby="nav-open-tab" tabindex="0">
                    <table class="table table-striped table-hover">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">DUE DATE</th>
                          <th scope="col">ASSIGNED TO</th>
                          <th scope="col">NAME</th>
                          <th scope="col">STATUS</th>
                          <th scope="col">PRIORITY</th>
                          <th scope="col">ACTION</th>
                        </tr>
                      </thead>
                      <tbody class="table-group-divider">
                        {% for task in openedTasks %}
                        <tr>
                          <th scope="row">{{ forloop.counter }}</th>
                          <td>{{task.taskDueDate}}</td>
                          <td>{{task.taskAssignee.username}}</td>
                          <td>{{task.taskName}}</td>
                          <td>{{task.taskCompletionStatus}}</td>
                          <td>{{task.taskPriority}}</td>
                          <td>
                            <a class="btn btn-info btn-sm" href="{% url 'task:viewTask' task.id %}" role="button">View</a>
                            <a class="btn btn-warning btn-sm" href="{% url 'task:updateTask' task.id %}" role="button">Update</a>
                            <a class="btn btn-danger btn-sm" href="{% url 'task:deleteTask' task.id %}" role="button">Delete</a>
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div> -->
                  <!-- <div class="tab-pane fade container p-2" id="nav-completed" role="tabpanel" aria-labelledby="nav-completed-tab" tabindex="0">
                    <table class="table table-striped table-hover">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">DUE DATE</th>
                          <th scope="col">ASSIGNED TO</th>
                          <th scope="col">NAME</th>
                          <th scope="col">STATUS</th>
                          <th scope="col">PRIORITY</th>
                          <th scope="col">ACTION</th>
                        </tr>
                      </thead>
                      <tbody class="table-group-divider">
                        {% for task in completedTasks %}
                        <tr>
                          <th scope="row">{{ forloop.counter }}</th>
                          <td>{{task.taskDueDate}}</td>
                          <td>{{task.taskAssignee.username}}</td>
                          <td>{{task.taskName}}</td>
                          <td>{{task.taskCompletionStatus}}</td>
                          <td>{{task.taskPriority}}</td>
                          <td>
                            <a class="btn btn-info btn-sm" href="{% url 'task:viewTask' task.id %}" role="button">View</a>
                            <a class="btn btn-warning btn-sm" href="{% url 'task:updateTask' task.id %}" role="button">Update</a>
                            <a class="btn btn-danger btn-sm" href="{% url 'task:deleteTask' task.id %}" role="button">Delete</a>
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div> -->
                </div>
                </div>
              
            
          </div>
          <!-- end of div content area -->


        </div>
      </div>
    
</body>
</html>