livestock_farming_management_system/financial/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#  Uniquely identify URL name for Financial module
app_name = "financial"

# Define URL patterns to be mapped respective view function of Financial module
urlpatterns = [
    path('',views.financialIndex,name='financialIndex'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('mainFinancial/',views.mainFinancial,name='mainFinancial'),
    path('mainFinancial/mainIncome/',views.mainIncome,name='mainIncome'),
    path('mainFinancial/mainExpense/',views.mainExpense,name='mainExpense'),
    path('mainFinancial/mainSaleTicket/',views.mainSaleTicket,name='mainSaleTicket'),
    path('mainFinancial/mainIncome/addIncome/',views.addIncome,name='addIncome'),
    path('mainFinancial/mainIncome/viewIncome/<str:id>',views.viewIncome,name='viewIncome'),
    path('mainFinancial/mainIncome/updateIncome/<str:id>',views.updateIncome,name='updateIncome'),
    path('mainFinancial/mainIncome/deleteIncome/<str:id>',views.deleteIncome,name='deleteIncome'),
    path('mainFinancial/mainIncome/searchIncome',views.searchIncome,name='searchIncome'),
    path('mainFinancial/mainExpense/addExpense/',views.addExpense,name='addExpense'),
    path('mainFinancial/mainExpense/viewExpense/<str:id>',views.viewExpense,name='viewExpense'),
    path('mainFinancial/mainExpense/updateExpense/<str:id>',views.updateExpense,name='updateExpense'),
    path('mainFinancial/mainExpense/deleteExpense/<str:id>',views.deleteExpense,name='deleteExpense'),
    path('mainFinancial/mainExpense/searchExpense',views.searchExpense,name='searchExpense'),
    path('mainFinancial/mainSaleTicket/addSaleTicket/',views.addSaleTicket,name='addSaleTicket'),
    path('mainFinancial/mainSaleTicket/searchSaleTicket',views.searchSaleTicket,name='searchSaleTicket'),
    path('mainFinancial/mainSaleTicket/updateSaleTicket/<str:id>',views.updateSaleTicket,name='updateSaleTicket'),
    path('mainFinancial/mainSaleTicket/cancelSaleTicket/<str:id>',views.cancelSaleTicket,name='cancelSaleTicket'),
    path('mainFinancial/mainSaleTicket/updateSoldAnimals/<str:id>',views.updateSoldAnimals,name='updateSoldAnimals'),
    path('mainFinancial/mainSaleTicket/viewSaleTicket/<str:id>',views.viewSaleTicket,name='viewSaleTicket'),
    path('mainFinancial/mainSaleTicket/viewSaleTicket/generatedPdf/<str:id>',views.generatedPdf,name='generatedPdf'),
    path('mainFinancial/mainSaleTicket/searchAnimalForSaleTicket/<str:key>',views.searchAnimalForSaleTicket,name='searchAnimalForSaleTicket'),

    
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

livestock_farming_management_system/livestock_farming_management_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('user.urls')),
    path('equipment/',include('equipment.urls')),
    path('task/',include('task.urls')),
    path('animal/',include('animal.urls')),
    path('financial/',include('financial.urls')),
    path('admin/', admin.site.urls),
]

livestock_farming_management_system/task/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#  Uniquely identify URL name for Task module
app_name = "task"

# Define URL patterns to be mapped respective view function of Task module
urlpatterns = [
    path('',views.taskIndex,name='taskIndex'),
    path('mainTask/',views.mainTask,name='mainTask'),
    path('addTask/',views.addTask,name='addTask'),
    path('viewTask/<str:id>',views.viewTask,name='viewTask'),
    path('updateTask/<str:id>',views.updateTask,name='updateTask'),
    path('deleteTask/<str:id>',views.deleteTask,name='deleteTask'),
    path('myTask/',views.myTask,name='myTask'),
    path('updateTaskStatus/<str:id>',views.updateTaskStatus,name='updateTaskStatus'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

livestock_farming_management_system/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#  Uniquely identify URL name for User module
app_name = "user"

# Define URL patterns for User module
urlpatterns = [
    path('',views.loginpage,name='loginpage'),
    path('home/',views.home,name='home'),
    path('logout/',views.logout,name='logout'),
    path('mainStaff/',views.mainStaff,name='mainStaff'),
    path('addStaff/',views.addStaff,name='addStaff'),
    path('staffProfile/<str:id>',views.staffProfile,name='staffProfile'),
    path('userProfile/<str:id>',views.userProfile,name='userProfile'),
    path('deactivateUser/<str:id>',views.deactivateUser,name='deactivateUser'),
    path('activateUser/<str:id>',views.activateUser,name='activateUser'),
    path('updateStaff/<str:id>',views.updateStaff,name='updateStaff'),
    path('deleteUser/<str:id>',views.deleteUser,name='deleteUser'),
    path('searchUser/',views.searchUser,name='searchUser'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

livestock_farming_management_system/user/models.py
from datetime import date
from django.db import models

# Create your models here.

# This model defines User table in database with fields related to user information.
class User(models.Model):

    email = models.CharField(max_length=150, unique=True)
    password = models.CharField(max_length=150)
    staffID = models.CharField(max_length=150)
    username = models.CharField(max_length=150, null=True)
    firstName = models.CharField(max_length=150, null=True)
    lastName = models.CharField(max_length=150, null=True)
    gender = models.CharField(max_length=150)
    dateOfBirth = models.DateField(null=True)
    address = models.CharField(max_length=150, null=True)
    maritalStatus = models.CharField(max_length=150)
    status = models.CharField(max_length=150)
    reasonDeactivation = models.CharField(max_length=150, default="Not Applicable", null=True)
    userRole = models.CharField(max_length=150)
    dateJoined = models.DateField(default=date.today)
    media = models.ImageField(upload_to='uploads/',default="", null=True)

    def save(self):
        super().save()

    def delete(self):
        super().delete()

    class Meta:
        db_table = 'User'

livestock_farming_management_system/user/views.py
import email
import json
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db import IntegrityError
from django.db.models import Q
from django.core.files.storage import FileSystemStorage
from django.views.decorators.csrf import csrf_exempt
from random import randint

from .models import User
from animal.models import Cattle,Sheep

# Create your views here.
    
# Handles the login functionality
def loginpage(request):
    if request.method == "POST":
        try:
            user = User.objects.get(email = request.POST['email'])
            if user.status == 'OPEN':
                if user.password == request.POST['password']:
                    request.session['EMAIL'] = user.email
                    request.session['LOGIN'] = 'YES'
                    request.session['ROLE'] = user.userRole
                    request.session['STAFFID'] = user.staffID
                    return redirect('user:home')
                else:
                    messages.success(request,'Incorrect User Credentials')
            else:
                messages.error(request,'This account has been deactivated. You cannot longer login using this account.')
        except User.DoesNotExist:
            messages.warning(request, 'Incorrect User Credentials')
    
    return render(request, 'login.html')


# Renders the homepage with a list of latest (top 4) cattles and sheeps to be displayed
def home(request):
    user = User.objects.get(email = request.session['EMAIL'])
    cattle=Cattle.objects.filter(~Q(cattleAttachment=''))
    newestCattle=cattle.order_by('-cattleDateRecorded')[:4]
    # print(newestCattle)
    sheep=Sheep.objects.filter(~Q(sheepAttachment=''))
    newestSheep=sheep.order_by('-sheepDateRecorded')[:4]
    # for x in allAnimals:
    #     randomAnimals.insert(randint(0,len(randomAnimals)),x)
    # print("random:",randomAnimals)
    return render(request,'homepage.html', {'user':user,'newestCattle':newestCattle,'newestSheep':newestSheep})


# logout from the session and redirect user to login page
def logout(request):
    request.session.flush()
    return redirect('user:loginpage')


# Renders main staff page with a list of staff records
def mainStaff(request):
    user = User.objects.get(email = request.session['EMAIL'])
    staff = User.objects.all()
    openedUser = User.objects.all().filter(status='OPEN')
    deactivatedUser = User.objects.all().filter(status='DEACTIVATED')
    return render(request, 'mainStaff.html', {'pagination':'STAFF', 'user':user, 'staff':staff, 'openedUser':openedUser, 'deactivatedUser':deactivatedUser})


# Handles the addition of new staff
def addStaff(request):
    user = User.objects.get(email = request.session['EMAIL'])

    try:

        if request.method=='POST':
            staffID=request.POST.get('staffID')
            email=request.POST.get('email')
            password='abcd1234'
            status='OPEN'
            role=request.POST.get('role')
            firstName=request.POST.get('firstname')
            lastName=request.POST.get('lastname')
            username=request.POST.get('username')
            User(email=email, staffID=staffID, password=password,userRole=role,status=status,firstName=firstName,lastName=lastName,username=username).save()
            messages.success(request,'Staff account is successfully created.', extra_tags='addStaff')
            return redirect('user:mainStaff')
            # return render(request, 'addStaff.html', {'pagination':'STAFF', 'user':user})
        else:
            return render(request, 'addStaff.html', {'pagination':'STAFF', 'user':user})

    except IntegrityError:
        messages.error(request,'Staff ID or email has been used before; Must be unique for each account.')
        return render(request, 'addStaff.html', {'pagination':'STAFF', 'user':user})


# Renders staff profile page with the information of that specific staff
def staffProfile(request, id):
    user = User.objects.get(email = request.session['EMAIL'])
    staff = User.objects.get(id = id)
    return render(request, 'staffProfile.html',{'user':user,'staff':staff,'pagination':'STAFF'})


# Renders the user profile page or handles the data update of the user
def userProfile(request, id):
    user = User.objects.get(id = id)
    
    if request.method=='POST':
        if 'AccountInfo' in request.POST:
            user.username = request.POST.get('username')
            user.email = request.POST.get('email')
            user.password = request.POST.get('password')
            del request.session['EMAIL']
            request.session['EMAIL'] = user.email
            user.save()
            messages.success(request,"Account is successfully updated")
            return redirect('user:userProfile', id)
        
        if 'ProfileInfo' in request.POST:
            user.firstName = request.POST.get('firstName')
            user.lastName = request.POST.get('lastName')
            user.dateOfBirth = request.POST.get('dateOfBirth')
            user.gender = request.POST.get('gender')
            user.maritalStatus = request.POST.get('maritalStatus')
            user.address = request.POST.get('address')

            user.save()
            messages.success(request,"Profile Info is successfully updated")
            return redirect('user:userProfile', id)

        if 'uploadPicture' in request.POST:
            user.media = request.FILES['imgupload']
            fss =FileSystemStorage()
            user.save()
            return redirect('user:userProfile', id)

    else:
        return render(request, 'userProfile.html',{'user':user})


# Handles deactivation of user account
@csrf_exempt
def deactivateUser(request, id):
    user = User.objects.get(id = id)
    reason=request.POST.get('reason')
    user.status="DEACTIVATED"
    user.reasonDeactivation=reason
    user.save()
    messages.success(request,"Account is deactivated")
    response = {'status': 1}
    return HttpResponse(json.dumps(response), content_type='application/json')


# Handles activation of user account
def activateUser(request, id):
    user = User.objects.get(id = id)
    # status = "DEACTIVATED"
    user.status="OPEN"
    user.reasonDeactivation="Not Applicable"
    user.save()
    messages.success(request,"Account is activated")
    return redirect('user:mainStaff')
    # return redirect('user:staffProfile', id)


# Handles the data update of staff information
def updateStaff(request, id):
    user = User.objects.get(id = id)
    if request.method=='POST':
        user.userRole = request.POST.get('role')
        user.dateJoined = request.POST.get('dateJoined')
        user.save()
        messages.success(request,"Account is successfully updated")
        return redirect('user:mainStaff')
    
    return render(request, 'updateStaff.html',{'user':user})


# Handles the deletion of user account
def deleteUser(request,id):
    try:
        user=User.objects.get(staffID=id)
        user.delete()
        messages.success(request,"User is deleted succesfully..!")
        return redirect('user:mainStaff')
    except User.DoesNotExist:
        messages.success(request,'No record of the user!' + id)
        return redirect('user:mainStaff')


# To search specific staff and render search staff page with related staff records if found.
def searchUser(request):
    user = User.objects.get(email = request.session['EMAIL'])
    if request.method == 'GET':
        query= request.GET.get('keyword')
        submitbutton= request.GET.get('submit')
        if query is not None:
            lookups= Q(staffID__icontains=query) | Q(username__icontains=query)
            results= User.objects.filter(lookups).distinct()
            context={'results': results,'submitbutton': submitbutton, 'pagination':'STAFF','user':user}
            return render(request, 'searchStaff.html', context)
        else:
            return render(request, 'searchStaff.html')
    
    else:
        return render(request, 'searchStaff.html', {'pagination':'STAFF','user':user}) 

livestock_farming_management_system/user/templates/navbar.html
<nav class="navbar sticky-top navbar-light justify-content-between" id="bg-navbar">
    <a class="navbar-brand px-3">Hello {{ user.username }}</a>  
    <a class="navbar-brand ">{% now "Y-m-d" %}</a>
    <a class="navbar-text px-3" style="text-decoration: none;"> {{ user.userRole }}</a>
  </nav>

livestock_farming_management_system/user/templates/staffProfile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Staff Profile</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    {% load static %}
    <link href="{% static 'sidebars.css' %}" rel="stylesheet">
    <style>
        #menu a:hover,
        #menu a.active{
            color: white;
            /* background:white; */
            background: #1D271A;
            /* border-right: 2px solid rgb(96, 122, 138); */
            width: auto;
        }
        .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      #sidebar{
        background-color: #223226;
      }

      #bg-navbar,
      #bg-navbar a{
        background-color: #960017;
        color: white;
      }

      #sidebar-title,
      #sidebar-title a
      {
        background: #7D000F;
        /* margin: -10px; */
        width: 100%;
        text-align: center;
        word-wrap:break-word;
        display: block;
        white-space: normal;
        color: white;
      }
      hr {
        width: 80%; 
        margin-right: auto;
        margin-left: auto;
        color: whitesmoke; 
        height: 1px; 
        background-color:whitesmoke; 
      }
    </style>
    
</head>
<body>
    {% include "sidebar.html" %}
          <!-- content area! -->
          <div class="col px-0 bg-light">
            <!-- Content area...
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Mollitia facilis enim blanditiis error magni inventore eaque sapiente vitae ipsa dicta eius quidem, facere et at minus alias quasi labore aliquid!</p>
            <p>Lorem ipsum dolor sit.</p> -->

            <!-- <nav class="navbar sticky-top navbar-light" id="bg-navbar">
              <div class="container-fluid">
                <a class="navbar-brand" href="#">{% now "Y-m-d" %} Hello {{ user.email }}</a>
              </div>
            </nav> -->
            {% include "navbar.html" %}

            <h3 class="p-3 bg-white">
              STAFF <br>
              <small class="text-muted">Management of Staff</small>
            </h3>
<!-- 
            <div class="alert alert-success" role="alert">
              kkk
            </div> -->

            <nav aria-label="breadcrumb" class="main-breadcrumb p-3">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{% url 'user:mainStaff' %}">Staff</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Staff Profile</li>
                </ol>
              </nav>

              {% if messages %}
        <div class="container">
        <hr>
        {% for msg in messages %}
        <!-- <b>{{msg}}</b> -->
        <div class="alert alert-success" role="alert">
          {{msg}}
        </div>
        {% endfor %}
        </div>
        <hr>
    {% endif %}
  
              <div class="row gutters-sm container bg-white p-2 m-3">
                <div class="col-md-4 mb-3">
                  <div class="card">
                    <div class="card-body">
                      <div class="d-flex flex-column align-items-center text-center">
                        <!-- <img src="" alt="Profile Pic" class="rounded-circle" width="150" id="imgSrc"> -->
                        {% if staff.media == null or staff.media == '' %}
                            <img src="{{MEDIA_URL}}default-profile-image.png" alt="Profile Pic" class="rounded-circle" width="150" id="imgSrc">
                        {% else %}
                            <!-- <img src="https://github.com/mdo.png" alt="Profile Pic" class="rounded-circle" width="150" id="imgSrc"> -->
                            <img src="{{MEDIA_URL}}{{staff.media}}" alt="Profile Pic" class="rounded-circle" width="150" id="imgSrc">
                            
                        {% endif %}
                        <div class="mt-3">
                          <h4 id="username">{{staff.username}}</h4>
                          <p class="text-secondary mb-1" id="staffID">{{staff.staffID}}</p>
                          <p class="text-muted font-size-sm" id="role">{{staff.userRole}}</p>
                          <!-- <button class="btn btn-warning" onclick="deactivateUser()">Deactivate</button> -->
                          <!-- <a class="btn btn-warning" href="{% url 'user:addStaff'%}" role="button">Deactivate</a> -->
                          {% if staff.status == 'DEACTIVATED' %}
                            <a class="btn btn-success" href="{% url 'user:activateUser' staff.id %}" role="button">Activate</a>
                          {% else %}
                            <button class="btn btn-warning" onclick="deactivateUser()">Deactivate</button>
                          {% endif %}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-md-8">
                  <div class="card mb-3">
                    <div class="card-body">
                      <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Full Name</h6>
                        </div>
                        <div class="col-sm-9 text-secondary" id="fullname">
                            {% if staff.firstName == null %}
                            <p> - </p>
                            {% else %}
                            <p>{{staff.firstName}} {{staff.lastName}}</p>
                            {% endif %}
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Email</h6>
                        </div>
                        <div class="col-sm-9 text-secondary" id="email">
                            <p>{{staff.email}}</p>
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Date Joined</h6>
                        </div>
                        <div class="col-sm-9 text-secondary" id="dateJoined">
                            <p>{{staff.dateJoined}}</p>
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Gender</h6>
                        </div>
                        <div class="col-sm-9 text-secondary" id="gender">
                            <p>{{staff.gender|default:'-'}}</p>
                        </div>
                      </div>
                      
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Birthdate</h6>
                        </div>
                        <div class="col-sm-9 text-secondary" id="birthdate">
                            {{staff.dateOfBirth|default_if_none:'-'}}
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Current Address</h6>
                        </div>
                        <div class="col-sm-9 text-secondary" id="currentAddress">
                            {{staff.address|default_if_none:'-'}}
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Account Status</h6>
                        </div>
                        <div class="col-sm-9 text-secondary" id="status">
                            <p>{{staff.status}}</p>
                        </div>
                      </div>
                      {% if staff.status == 'DEACTIVATED' %}
                      <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Reason of Deactivation</h6>
                        </div>
                        <div class="col-sm-9 text-secondary" id="reasonDeactivation">
                            <p>{{staff.reasonDeactivation}}</p>
                        </div>
                      </div>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>


              <div class="row gutters-sm container bg-white p-2 m-3">
                <h3>Task</h3>
                
                <table class="table table-striped table-hover">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">DUE DATE</th>
                      <th scope="col">ASSIGNED TO</th>
                      <th scope="col">NAME</th>
                      <th scope="col">STATUS</th>
                      <th scope="col">PRIORITY</th>
                      <th scope="col">ACTION</th>
                    </tr>
                  </thead>
                  <tbody class="table-group-divider">
                    {% for task in staff.taskAssignee.all %}
                    <tr>
                      <th scope="row">{{ forloop.counter }}</th>
                      <td>{{task.taskDueDate}}</td>
                      <td>{{task.taskAssignee.username}}</td>
                      <td>{{task.taskName}}</td>
                      <td>{{task.taskCompletionStatus}}</td>
                      <td>{{task.taskPriority}}</td>
                      <td>
                        <a class="btn btn-info btn-sm" href="{% url 'task:viewTask' task.id %}" role="button">View</a>
                        <a class="btn btn-warning btn-sm" href="{% url 'task:updateTask' task.id %}" role="button">Update</a>
                        <a class="btn btn-danger btn-sm" href="{% url 'task:deleteTask' task.id %}" role="button">Delete</a>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
              
          </div>
          <!-- above is the closed div to content area! -->

          


        </div>
      </div>


      <script>
        var currentEmail = "{{request.session.EMAIL}}";
        function deactivateUser(){
            
            if ("{{staff.email}}" != currentEmail) {
                if (confirm("Press OK to confirm the deactivation!")) {
                    // document.location.href = "{% url 'user:deactivateUser' staff.id %}";

                    let reason = prompt("Reason for deactivation?", "Resigned");
                    if (reason != null) {
                      alert("Reason is: "+reason);
                      $.ajax({
                        type: "POST",
                        url: "{% url 'user:deactivateUser' staff.id %}",
                        data: {
                            "reason": reason,
                        },
                        dataType: "json",
                        success: function (data) {
                            // any process in data
                            // alert("successfull")
                            if(data.status == 1){
                              document.location.href = "{% url 'user:staffProfile' staff.id %}";
                            }
                        },
                        failure: function () {
                            // alert("failure");
                        }
                      });
                    }

                    // window.location.reload();
      

                }else{
                  alert("You canceled deactivating this account!");
                  event.preventDefault();
                }
                } else {
                alert("You cannot deactivate your own account! Please refer to the management on this matter.")
                }
        };
      </script>
    
</body>
</html>