livestock_farming_management_system/equipment/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#  Uniquely identify URL name for Equipment module
app_name = "equipment"

# Define URL patterns to be mapped respective view function of Equipment module
urlpatterns = [
    path('',views.equipmentIndex,name='equipmentIndex'),
    path('mainEquipment/',views.mainEquipment,name='mainEquipment'),
    path('addEquipment/',views.addEquipment,name='addEquipment'),
    path('viewEquipment/<str:id>',views.viewEquipment,name='viewEquipment'),
    path('updateEquipment/<str:id>',views.updateEquipment,name='updateEquipment'),
    path('deleteEquipment/<str:id>',views.deleteEquipment,name='deleteEquipment'),
    path('searchEquipment/',views.searchEquipment,name='searchEquipment'),
    path('equipmentUsage/',views.equipmentUsage,name='equipmentUsage'),
    path('addEquipmentUsage/',views.addEquipmentUsage,name='addEquipmentUsage'),
    path('updateEquipmentUsage/<str:id>',views.updateEquipmentUsage,name='updateEquipmentUsage'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

livestock_farming_management_system/livestock_farming_management_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('user.urls')),
    path('equipment/',include('equipment.urls')),
    path('task/',include('task.urls')),
    path('animal/',include('animal.urls')),
    path('financial/',include('financial.urls')),
    path('admin/', admin.site.urls),
]

livestock_farming_management_system/task/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#  Uniquely identify URL name for Task module
app_name = "task"

# Define URL patterns to be mapped respective view function of Task module
urlpatterns = [
    path('',views.taskIndex,name='taskIndex'),
    path('mainTask/',views.mainTask,name='mainTask'),
    path('addTask/',views.addTask,name='addTask'),
    path('viewTask/<str:id>',views.viewTask,name='viewTask'),
    path('updateTask/<str:id>',views.updateTask,name='updateTask'),
    path('deleteTask/<str:id>',views.deleteTask,name='deleteTask'),
    path('myTask/',views.myTask,name='myTask'),
    path('updateTaskStatus/<str:id>',views.updateTaskStatus,name='updateTaskStatus'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

livestock_farming_management_system/task/models.py
from django.db import models
from user.models import User

# This model defines Task table in database with fields related to task information.
class Task(models.Model):

    taskName = models.CharField(max_length=250)
    taskPriority = models.CharField(max_length=250)
    taskCategory = models.CharField(max_length=250)
    taskDetails = models.CharField(max_length=250)
    taskDueDate = models.DateField()
    taskCompletionStatus = models.CharField(max_length=250)
    taskAttachment = models.FileField(upload_to='task/', null=True)
    taskAssignee = models.ForeignKey(User, on_delete=models.CASCADE, related_name="taskAssignee")
    taskAssigner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="taskAssigner")

    def save(self):
        super().save()

    def delete(self):
        super().delete()

    class Meta:
        db_table = 'Task'

livestock_farming_management_system/task/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db import IntegrityError
from django.core.files.storage import FileSystemStorage
from task.models import Task

from user.models import User

# Represents the homepage or root URL of Task module. It will redirect system to the mainTask view function.
def taskIndex(request):
    return redirect('task:mainTask')


# Renders main task page with all records of task
def mainTask(request):
    user = User.objects.get(email = request.session['EMAIL'])
    tasks=Task.objects.all()
    openedTasks=Task.objects.exclude(taskCompletionStatus='COMPLETED')
    completedTasks=Task.objects.filter(taskCompletionStatus='COMPLETED')
    return render(request, 'mainTask.html', {'user':user,'tasks':tasks,'openedTasks':openedTasks,'completedTasks':completedTasks})


# Handles addition of new task or renders add task form
def addTask(request):
    user = User.objects.get(email = request.session['EMAIL'])
    staff=User.objects.all()
    try:

        if request.method=='POST':
            taskName=request.POST.get('taskName')
            taskPriority=request.POST.get('priority')
            taskCategory=request.POST.get('taskCategory')
            taskDetails=request.POST.get('details')
            taskDueDate=request.POST.get('dueDate')
            taskCompletionStatus=request.POST.get('completionStatus')
            taskAssigner=user
            selectedUserID=request.POST.get('taskAssignee')
            assignee = User.objects.get(id = selectedUserID)
            taskAttachment = request.FILES.get('fileupload', None)
            fss =FileSystemStorage()
            Task(taskName=taskName,taskPriority=taskPriority,taskCategory=taskCategory,taskDetails=taskDetails,taskDueDate=taskDueDate,taskCompletionStatus=taskCompletionStatus,taskAssigner=taskAssigner,taskAssignee=assignee,taskAttachment=taskAttachment).save()
            messages.success(request,'Task is successfully created.', extra_tags='addTask')
            return redirect('task:mainTask')
        else:
            return render(request, 'addTask.html', {'user':user,'staff':staff})

    except IntegrityError:
        messages.error(request,'Error Task')
        return render(request, 'addTask.html', {'user':user,'staff':staff})


# Renders view task page with information of a specific task
def viewTask(request,id):
    user = User.objects.get(email = request.session['EMAIL'])
    task = Task.objects.get(id=id)
    return render(request, 'viewTask.html', {'user':user,'task':task})


# Handles update operation of a specific task
def updateTask(request,id):
    user = User.objects.get(email = request.session['EMAIL'])
    task = Task.objects.get(id=id)
    staff=User.objects.all()
    if request.method=='POST':
        task.taskName=request.POST.get('taskName')
        task.taskPriority=request.POST.get('priority')
        task.taskCategory=request.POST.get('taskCategory')
        task.taskDetails=request.POST.get('details')
        task.taskDueDate=request.POST.get('dueDate')
        selectedUserID=request.POST.get('taskAssignee')
        task.assignee = User.objects.get(id = selectedUserID)
        # task.taskAttachment = request.FILES['fileupload']
        if len(request.FILES) != 0:
            if task.taskAttachment!=None or task.taskAttachment!='':
                task.taskAttachment.delete()
            task.taskAttachment = request.FILES['fileupload']
            fss =FileSystemStorage()
        
        task.save()
        messages.success(request,"Task is successfully updated")
        return redirect('task:mainTask')
    
    return render(request, 'updateTask.html', {'user':user,'task':task,'staff':staff})


# Handles deletion operation of a specific task
def deleteTask(request,id):
    try:
        user = User.objects.get(email = request.session['EMAIL'])
        task = Task.objects.get(id=id)
        if request.method=='POST':
            if task.taskAttachment!=None or task.taskAttachment!='':
                task.taskAttachment.delete()
            task.delete()
            messages.success(request,"Task is deleted succesfully..!")
            return redirect('task:mainTask')
        else:
            return render(request, 'deleteTask.html', {'user':user,'task':task})

    except Task.DoesNotExist:
        messages.success(request,'No record of the task!' + id)
        return redirect('task:mainTask')


# Renders task page with all task records related to a user
def myTask(request):
    user = User.objects.get(email = request.session['EMAIL'])
    userOpenedTasks=Task.objects.filter(taskAssignee = user.id).exclude(taskCompletionStatus='COMPLETED')
    userCompletedTasks = Task.objects.all().filter(taskAssignee = user.id, taskCompletionStatus='COMPLETED')
    # completedTasks=Task.objects.filter(taskCompletionStatus='COMPLETED')
    return render(request, 'myTask.html', {'user':user,'userOpenedTasks':userOpenedTasks,'userCompletedTasks':userCompletedTasks})


# Handles update operation of task status by a user
def updateTaskStatus(request,id):
    user=User.objects.get(email = request.session['EMAIL'])
    taskInfo=Task.objects.get(id = id)
    if request.method=='POST':
        taskInfo.taskCompletionStatus=request.POST.get('taskCompletionStatus')
        taskInfo.save()
        messages.success(request,"Task progress status is successfully updated")
        return redirect('task:myTask')

    return render(request, 'taskStatus.html', {'user':user,'task':taskInfo})

livestock_farming_management_system/task/templates/mainTask.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main Task</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <style>
        #menu a:hover,
        #menu a.active{
            color: white;
            /* background:white; */
            background: #1D271A;
            /* border-right: 2px solid rgb(96, 122, 138); */
            width: auto;
        }
        .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      #sidebar{
        background-color: #223226;
      }

      #bg-navbar,
      #bg-navbar a{
        background-color: #960017;
        color: white;
      }

      #sidebar-title,
      #sidebar-title a
      {
        background: #7D000F;
        /* margin: -10px; */
        width: 100%;
        text-align: center;
        word-wrap:break-word;
        display: block;
        white-space: normal;
        color: white;
      }
      hr {
        width: 80%; 
        margin-right: auto;
        margin-left: auto;
        color: whitesmoke; 
        height: 1px; 
        background-color:whitesmoke; 
      }
    </style>
    
</head>
<body>
    {% include "sidebarTask.html" %}
          <!-- content area! -->
          <div class="col px-0 bg-light">

            <!-- <nav class="navbar sticky-top navbar-light" id="bg-navbar">
              <div class="container-fluid">
                <a class="navbar-brand" href="#">{% now "Y-m-d" %} Hello {{ user.username }}</a>
              </div>
            </nav> -->
            {% include "navbar.html" %}
    
                <h3 class="p-3 bg-white">
                  TASK <br>
                  <small class="text-muted">Management of Task</small>
                </h3>
    
                <!-- <nav class="navbar p-3">
                  <div class="container-fluid">
                    <a class="navbar-brand"></a>
                    <form class="d-flex" role="search" method="get" action="{% url 'equipment:searchEquipment' %}" value="{{request.GET.keyword}}">
                      <input class="form-control me-2" type="search" name="keyword" id="keyword" value="{{request.GET.keyword}}" placeholder="Search" aria-label="Search">
                      <button class="btn btn-outline-success" type="submit" name="submit" value="Search">Search</button>
                    </form>
                  </div>
                </nav> -->
    
                {% if messages %}
            <div class="container">
            <hr>
            {% for msg in messages %}
            <div class="alert alert-success" role="alert">
              {{msg}}
            </div>
            <!-- <b>{{msg}}</b> -->
            {% endfor %}
            </div>
            <hr>
        {% endif %}
    
                {% if messages %}
                    <div class="container">
                    {% for msg in messages %}
                      {% if "addStaff" in message.tags %}
                        <div class="alert alert-success" role="alert">
                          {{msg}}
                        </div>
                      {% endif %}
                    {% endfor %}
                    </div>
                    <hr>
                {% endif %}
    <!-- 
                <div class="alert alert-success" role="alert">
                  kkk
                </div> -->
    
                <div class="container bg-white">
                  {% if user.userRole == 'STAFF LEADER' or user.userRole == 'OWNER' %}
                    <a class="btn btn-primary m-3" href="{% url 'task:addTask' %}" role="button">Add Task</a>
                  {% endif %}
                  <a class="btn btn-primary m-3" href="{% url 'task:myTask' %}" role="button">Your Task</a>
    
                <nav class="container p-2">
                  <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <button class="nav-link active" id="nav-general-tab" data-bs-toggle="tab" data-bs-target="#nav-general" type="button" role="tab" aria-controls="nav-general" aria-selected="true">General</button>
                    <button class="nav-link" id="nav-open-tab" data-bs-toggle="tab" data-bs-target="#nav-open" type="button" role="tab" aria-controls="nav-open" aria-selected="false">Open</button>
                    <button class="nav-link" id="nav-completed-tab" data-bs-toggle="tab" data-bs-target="#nav-completed" type="button" role="tab" aria-controls="nav-completed" aria-selected="false">Completed</button>
                  </div>
                </nav>
                <div class="tab-content table-responsive" id="nav-tabContent">
                  <div class="tab-pane fade show active container p-2" id="nav-general" role="tabpanel" aria-labelledby="nav-general-tab" tabindex="0">
                    <table class="table table-striped table-hover">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">DUE DATE</th>
                          <th scope="col">ASSIGNED TO</th>
                          <th scope="col">ASSIGNER</th>
                          <th scope="col">NAME</th>
                          <th scope="col">STATUS</th>
                          <th scope="col">PRIORITY</th>
                          <th scope="col">ACTION</th>
                        </tr>
                      </thead>
                      <tbody class="table-group-divider">
                        {% for task in tasks %}
                        <tr>
                          <th scope="row">{{ forloop.counter }}</th>
                          <td>{{task.taskDueDate}}</td>
                          <td>{{task.taskAssignee.username}}</td>
                          <td>{{task.taskAssigner.username}}</td>
                          <td>{{task.taskName}}</td>
                          <td>{{task.taskCompletionStatus}}</td>
                          <td>{{task.taskPriority}}</td>
                          <td>
                            <a class="btn btn-info btn-sm" href="{% url 'task:viewTask' task.id %}" role="button">View</a>
                            {% if task.taskAssigner.email == user.email %}
                            <a class="btn btn-warning btn-sm" href="{% url 'task:updateTask' task.id %}" role="button">Update</a>
                            <a class="btn btn-danger btn-sm" href="{% url 'task:deleteTask' task.id %}" role="button">Delete</a>
                            {% endif %}
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                  <div class="tab-pane fade container p-2" id="nav-open" role="tabpanel" aria-labelledby="nav-open-tab" tabindex="0">
                    <table class="table table-striped table-hover">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">DUE DATE</th>
                          <th scope="col">ASSIGNED TO</th>
                          <th scope="col">NAME</th>
                          <th scope="col">STATUS</th>
                          <th scope="col">PRIORITY</th>
                          <th scope="col">ACTION</th>
                        </tr>
                      </thead>
                      <tbody class="table-group-divider">
                        {% for task in openedTasks %}
                        <tr>
                          <th scope="row">{{ forloop.counter }}</th>
                          <td>{{task.taskDueDate}}</td>
                          <td>{{task.taskAssignee.username}}</td>
                          <td>{{task.taskName}}</td>
                          <td>{{task.taskCompletionStatus}}</td>
                          <td>{{task.taskPriority}}</td>
                          <td>
                            <a class="btn btn-info btn-sm" href="{% url 'task:viewTask' task.id %}" role="button">View</a>
                            <a class="btn btn-warning btn-sm" href="{% url 'task:updateTask' task.id %}" role="button">Update</a>
                            <a class="btn btn-danger btn-sm" href="{% url 'task:deleteTask' task.id %}" role="button">Delete</a>
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                  <div class="tab-pane fade container p-2" id="nav-completed" role="tabpanel" aria-labelledby="nav-completed-tab" tabindex="0">
                    <table class="table table-striped table-hover">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">DUE DATE</th>
                          <th scope="col">ASSIGNED TO</th>
                          <th scope="col">NAME</th>
                          <th scope="col">STATUS</th>
                          <th scope="col">PRIORITY</th>
                          <th scope="col">ACTION</th>
                        </tr>
                      </thead>
                      <tbody class="table-group-divider">
                        {% for task in completedTasks %}
                        <tr>
                          <th scope="row">{{ forloop.counter }}</th>
                          <td>{{task.taskDueDate}}</td>
                          <td>{{task.taskAssignee.username}}</td>
                          <td>{{task.taskName}}</td>
                          <td>{{task.taskCompletionStatus}}</td>
                          <td>{{task.taskPriority}}</td>
                          <td>
                            <a class="btn btn-info btn-sm" href="{% url 'task:viewTask' task.id %}" role="button">View</a>
                            <a class="btn btn-warning btn-sm" href="{% url 'task:updateTask' task.id %}" role="button">Update</a>
                            <a class="btn btn-danger btn-sm" href="{% url 'task:deleteTask' task.id %}" role="button">Delete</a>
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
                </div>
              
            
          </div>
          <!-- end of div content area -->


        </div>
      </div>
    
</body>
</html>

livestock_farming_management_system/task/templates/myTask.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Task</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <style>
        #menu a:hover,
        #menu a.active{
            color: white;
            /* background:white; */
            background: #1D271A;
            /* border-right: 2px solid rgb(96, 122, 138); */
            width: auto;
        }
        .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      #sidebar{
        background-color: #223226;
      }

      #bg-navbar,
      #bg-navbar a{
        background-color: #960017;
        color: white;
      }

      #sidebar-title,
      #sidebar-title a
      {
        background: #7D000F;
        /* margin: -10px; */
        width: 100%;
        text-align: center;
        word-wrap:break-word;
        display: block;
        white-space: normal;
        color: white;
      }
      hr {
        width: 80%; 
        margin-right: auto;
        margin-left: auto;
        color: whitesmoke; 
        height: 1px; 
        background-color:whitesmoke; 
      }
    </style>
    
</head>
<body>
    {% include "sidebarTask.html" %}
          <!-- content area! -->
          <div class="col px-0 bg-light">

            <!-- <nav class="navbar sticky-top navbar-light" id="bg-navbar">
              <div class="container-fluid">
                <a class="navbar-brand" href="#">{% now "Y-m-d" %} Hello {{ user.username }}</a>
              </div>
            </nav> -->
            {% include "navbar.html" %}
    
                <h3 class="p-3 bg-white">
                  YOUR TASK <br>
                  <small class="text-muted">Management of Task</small>
                </h3>
    
                <!-- <nav class="navbar p-3">
                  <div class="container-fluid">
                    <a class="navbar-brand"></a>
                    <form class="d-flex" role="search" method="get" action="{% url 'equipment:searchEquipment' %}" value="{{request.GET.keyword}}">
                      <input class="form-control me-2" type="search" name="keyword" id="keyword" value="{{request.GET.keyword}}" placeholder="Search" aria-label="Search">
                      <button class="btn btn-outline-success" type="submit" name="submit" value="Search">Search</button>
                    </form>
                  </div>
                </nav> -->
    
                {% if messages %}
            <div class="container">
            <hr>
            {% for msg in messages %}
            <div class="alert alert-success" role="alert">
              {{msg}}
            </div>
            {% endfor %}
            </div>
            <hr>
        {% endif %}
    
                {% if messages %}
                    <div class="container">
                    {% for msg in messages %}
                      {% if "addStaff" in message.tags %}
                        <div class="alert alert-success" role="alert">
                          {{msg}}
                        </div>
                      {% endif %}
                    {% endfor %}
                    </div>
                    <hr>
                {% endif %}
    <!-- 
                <div class="alert alert-success" role="alert">
                  kkk
                </div> -->

                <div class="container p-2">
                  <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                      <li class="breadcrumb-item"><a href="{% url 'task:mainTask' %}">Main Task</a></li>
                      <li class="breadcrumb-item active" aria-current="page">Your Task</li>
                    </ol>
                  </nav>
                </div>
    
                <div class="container bg-white">
                  <!-- <a class="btn btn-primary m-3" href="{% url 'task:addTask' %}" role="button">Add Task</a>
                  <a class="btn btn-primary m-3" href="{% url 'equipment:equipmentUsage' %}" role="button">Your Task</a> -->
    
                <nav class="container p-2">
                  <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <button class="nav-link active" id="nav-open-tab" data-bs-toggle="tab" data-bs-target="#nav-open" type="button" role="tab" aria-controls="nav-open" aria-selected="true">Open</button>
                    <button class="nav-link" id="nav-completed-tab" data-bs-toggle="tab" data-bs-target="#nav-completed" type="button" role="tab" aria-controls="nav-completed" aria-selected="false">Completed</button>
                  </div>
                </nav>
                <div class="tab-content" id="nav-tabContent">
                  <div class="tab-pane fade show active container p-2" id="nav-open" role="tabpanel" aria-labelledby="nav-open-tab" tabindex="0">
                    <div class="col-sm-10">
                      {% if not userOpenedTasks.all %}
                      <div class="alert alert-warning" role="alert">
                        No records found!
                      </div>
                      {% endif %}
                    </div>
                    <table class="table table-striped table-hover">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">DUE DATE</th>
                          <th scope="col">ASSIGNED TO</th>
                          <th scope="col">NAME</th>
                          <th scope="col">STATUS</th>
                          <th scope="col">PRIORITY</th>
                          <th scope="col">ACTION</th>
                        </tr>
                      </thead>
                      <tbody class="table-group-divider">
                        {% for task in userOpenedTasks %}
                        <tr>
                          <th scope="row">{{ forloop.counter }}</th>
                          <td>{{task.taskDueDate}}</td>
                          <td>{{task.taskAssignee.username}}</td>
                          <td>{{task.taskName}}</td>
                          <td>{{task.taskCompletionStatus}}</td>
                          <td>{{task.taskPriority}}</td>
                          <td>
                            <a class="btn btn-info btn-sm" href="{% url 'task:viewTask' task.id %}" role="button">View</a>
                            <a class="btn btn-warning btn-sm" href="{% url 'task:updateTaskStatus' task.id %}" role="button">Update Status</a>
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                  <div class="tab-pane fade container p-2" id="nav-completed" role="tabpanel" aria-labelledby="nav-completed-tab" tabindex="0">
                    <div class="col-sm-10">
                      {% if not userCompletedTasks.all %}
                      <div class="alert alert-warning" role="alert">
                        No records found!
                      </div>
                      {% endif %}
                    </div>
                    <table class="table table-striped table-hover">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">DUE DATE</th>
                          <th scope="col">ASSIGNED TO</th>
                          <th scope="col">NAME</th>
                          <th scope="col">STATUS</th>
                          <th scope="col">PRIORITY</th>
                          <th scope="col">ACTION</th>
                        </tr>
                      </thead>
                      <tbody class="table-group-divider">
                        {% for task in userCompletedTasks %}
                        <tr>
                          <th scope="row">{{ forloop.counter }}</th>
                          <td>{{task.taskDueDate}}</td>
                          <td>{{task.taskAssignee.username}}</td>
                          <td>{{task.taskName}}</td>
                          <td>{{task.taskCompletionStatus}}</td>
                          <td>{{task.taskPriority}}</td>
                          <td>
                            <a class="btn btn-info btn-sm" href="{% url 'task:viewTask' task.id %}" role="button">View</a>
                            <a class="btn btn-warning btn-sm" href="{% url 'task:updateTaskStatus' task.id %}" role="button">Update Status</a>
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
                </div>
              
            
          </div>
          <!-- end of div content area -->


        </div>
      </div>
    
</body>
</html>

livestock_farming_management_system/task/templates/navbar.html
<nav class="navbar sticky-top navbar-light justify-content-between" id="bg-navbar">
    <a class="navbar-brand px-3">Hello {{ user.username }}</a>  
    <a class="navbar-brand ">{% now "Y-m-d" %}</a>
    <a class="navbar-text px-3" style="text-decoration: none;"> {{ user.userRole }}</a>
  </nav>